version: '3'

services:
  namesrv:
    image: apache/rocketmq:4.9.2
    container_name: rocketmq-nameserver
    environment:
      - "JAVA_OPT=-Duser.home=/root"
    ports:
      - "9876:9876"
    volumes:
      - ./data/namesrv/logs:/root/logs
      - ./data/namesrv/store:/root/store
    command: sh -c "cd /rocketmq/bin && ./mqnamesrv"

  broker:
    image: apache/rocketmq:4.9.2
    container_name: rocketmq-broker
    environment:
      - "JAVA_OPT=-Duser.home=/root"
      - "NAMESRV_ADDR=rocketmq-nameserver:9876"
      - "BROKER_CLUSTER_NAME=DefaultCluster"
      - "BROKER_ID=0"
      - "BROKER_IP1=127.0.0.1"
      - "MQ_HOME=/rocketmq"
      - "ROCKETMQ_OPTS=-Duser.home=/root"
    ports:
      - "10911:10911"
    volumes:
      - ./data/broker/logs:/root/logs
      - ./data/broker/store:/root/store
    depends_on:
      - namesrv
    command: sh -c "cd /rocketmq/bin && ./mqbroker -n rocketmq-nameserver:9876"
